use image::{AnimationDecoder, codecs::gif::GifDecoder};

pub fn get(n: &str) -> usize {
  match POKEMON.iter().position(|x| x == &n) {
    Some(i) => i,
    None => 0,
  }
}

pub fn gif(n: &str) -> Vec<image::Frame> {
  let i = get(n);
  let buf = get_gif(i);
  let buf = std::io::Cursor::new(&buf);
  let decoder = GifDecoder::new(buf).unwrap();
  let frames = decoder.into_frames();
  let frames = frames.collect_frames().unwrap();
  frames
}

// Use a HashMap to store the vikings' health points.
static POKEMON: [&'static str; 650] = [
  "Egg",
  "Bulbasaur",
  "Ivysaur",
  "Venusaur",
  "Charmander",
  "Charmeleon",
  "Charizard",
  "Squirtle",
  "Wartortle",
  "Blastoise",
  "Caterpie",
  "Metapod",
  "Butterfree",
  "Weedle",
  "Kakuna",
  "Beedrill",
  "Pidgey",
  "Pidgeotto",
  "Pidgeot",
  "Rattata",
  "Raticate",
  "Spearow",
  "Fearow",
  "Ekans",
  "Arbok",
  "Pikachu",
  "Raichu",
  "Sandshrew",
  "Sandslash",
  "Nidoran♀",
  "Nidorina",
  "Nidoqueen",
  "Nidoran♂",
  "Nidorino",
  "Nidoking",
  "Clefairy",
  "Clefable",
  "Vulpix",
  "Ninetales",
  "Jigglypuff",
  "Wigglytuff",
  "Zubat",
  "Golbat",
  "Oddish",
  "Gloom",
  "Vileplume",
  "Paras",
  "Parasect",
  "Venonat",
  "Venomoth",
  "Diglett",
  "Dugtrio",
  "Meowth",
  "Persian",
  "Psyduck",
  "Golduck",
  "Mankey",
  "Primeape",
  "Growlithe",
  "Arcanine",
  "Poliwag",
  "Poliwhirl",
  "Poliwrath",
  "Abra",
  "Kadabra",
  "Alakazam",
  "Machop",
  "Machoke",
  "Machamp",
  "Bellsprout",
  "Weepinbell",
  "Victreebel",
  "Tentacool",
  "Tentacruel",
  "Geodude",
  "Graveler",
  "Golem",
  "Ponyta",
  "Rapidash",
  "Slowpoke",
  "Slowbro",
  "Magnemite",
  "Magneton",
  "Farfetch'd",
  "Doduo",
  "Dodrio",
  "Seel",
  "Dewgong",
  "Grimer",
  "Muk",
  "Shellder",
  "Cloyster",
  "Gastly",
  "Haunter",
  "Gengar",
  "Onix",
  "Drowzee",
  "Hypno",
  "Krabby",
  "Kingler",
  "Voltorb",
  "Electrode",
  "Exeggcute",
  "Exeggutor",
  "Cubone",
  "Marowak",
  "Hitmonlee",
  "Hitmonchan",
  "Lickitung",
  "Koffing",
  "Weezing",
  "Rhyhorn",
  "Rhydon",
  "Chansey",
  "Tangela",
  "Kangaskhan",
  "Horsea",
  "Seadra",
  "Goldeen",
  "Seaking",
  "Staryu",
  "Starmie",
  "Mr. mime",
  "Scyther",
  "Jynx",
  "Electabuzz",
  "Magmar",
  "Pinsir",
  "Tauros",
  "Magikarp",
  "Gyarados",
  "Lapras",
  "Ditto",
  "Eevee",
  "Vaporeon",
  "Jolteon",
  "Flareon",
  "Porygon",
  "Omanyte",
  "Omastar",
  "Kabuto",
  "Kabutops",
  "Aerodactyl",
  "Snorlax",
  "Articuno",
  "Zapdos",
  "Moltres",
  "Dratini",
  "Dragonair",
  "Dragonite",
  "Mewtwo",
  "Mew",
  "Chikorita",
  "Bayleef",
  "Meganium",
  "Cyndaquil",
  "Quilava",
  "Typhlosion",
  "Totodile",
  "Croconaw",
  "Feraligatr",
  "Sentret",
  "Furret",
  "Hoothoot",
  "Noctowl",
  "Ledyba",
  "Ledian",
  "Spinarak",
  "Ariados",
  "Crobat",
  "Chinchou",
  "Lanturn",
  "Pichu",
  "Cleffa",
  "Igglybuff",
  "Togepi",
  "Togetic",
  "Natu",
  "Xatu",
  "Mareep",
  "Flaaffy",
  "Ampharos",
  "Bellossom",
  "Marill",
  "Azumarill",
  "Sudowoodo",
  "Politoed",
  "Hoppip",
  "Skiploom",
  "Jumpluff",
  "Aipom",
  "Sunkern",
  "Sunflora",
  "Yanma",
  "Wooper",
  "Quagsire",
  "Espeon",
  "Umbreon",
  "Murkrow",
  "Slowking",
  "Misdreavus",
  "Unown",
  "Wobbuffet",
  "Girafarig",
  "Pineco",
  "Forretress",
  "Dunsparce",
  "Gligar",
  "Steelix",
  "Snubbull",
  "Granbull",
  "Qwilfish",
  "Scizor",
  "Shuckle",
  "Heracross",
  "Sneasel",
  "Teddiursa",
  "Ursaring",
  "Slugma",
  "Magcargo",
  "Swinub",
  "Piloswine",
  "Corsola",
  "Remoraid",
  "Octillery",
  "Delibird",
  "Mantine",
  "Skarmory",
  "Houndour",
  "Houndoom",
  "Kingdra",
  "Phanpy",
  "Donphan",
  "Porygon2",
  "Stantler",
  "Smeargle",
  "Tyrogue",
  "Hitmontop",
  "Smoochum",
  "Elekid",
  "Magby",
  "Miltank",
  "Blissey",
  "Raikou",
  "Entei",
  "Suicune",
  "Larvitar",
  "Pupitar",
  "Tyranitar",
  "Lugia",
  "Ho-oh",
  "Celebi",
  "Treecko",
  "Grovyle",
  "Sceptile",
  "Torchic",
  "Combusken",
  "Blaziken",
  "Mudkip",
  "Marshtomp",
  "Swampert",
  "Poochyena",
  "Mightyena",
  "Zigzagoon",
  "Linoone",
  "Wurmple",
  "Silcoon",
  "Beautifly",
  "Cascoon",
  "Dustox",
  "Lotad",
  "Lombre",
  "Ludicolo",
  "Seedot",
  "Nuzleaf",
  "Shiftry",
  "Taillow",
  "Swellow",
  "Wingull",
  "Pelipper",
  "Ralts",
  "Kirlia",
  "Gardevoir",
  "Surskit",
  "Masquerain",
  "Shroomish",
  "Breloom",
  "Slakoth",
  "Vigoroth",
  "Slaking",
  "Nincada",
  "Ninjask",
  "Shedinja",
  "Whismur",
  "Loudred",
  "Exploud",
  "Makuhita",
  "Hariyama",
  "Azurill",
  "Nosepass",
  "Skitty",
  "Delcatty",
  "Sableye",
  "Mawile",
  "Aron",
  "Lairon",
  "Aggron",
  "Meditite",
  "Medicham",
  "Electrike",
  "Manectric",
  "Plusle",
  "Minun",
  "Volbeat",
  "Illumise",
  "Roselia",
  "Gulpin",
  "Swalot",
  "Carvanha",
  "Sharpedo",
  "Wailmer",
  "Wailord",
  "Numel",
  "Camerupt",
  "Torkoal",
  "Spoink",
  "Grumpig",
  "Spinda",
  "Trapinch",
  "Vibrava",
  "Flygon",
  "Cacnea",
  "Cacturne",
  "Swablu",
  "Altaria",
  "Zangoose",
  "Seviper",
  "Lunatone",
  "Solrock",
  "Barboach",
  "Whiscash",
  "Corphish",
  "Crawdaunt",
  "Baltoy",
  "Claydol",
  "Lileep",
  "Cradily",
  "Anorith",
  "Armaldo",
  "Feebas",
  "Milotic",
  "Castform",
  "Kecleon",
  "Shuppet",
  "Banette",
  "Duskull",
  "Dusclops",
  "Tropius",
  "Chimecho",
  "Absol",
  "Wynaut",
  "Snorunt",
  "Glalie",
  "Spheal",
  "Sealeo",
  "Walrein",
  "Clamperl",
  "Huntail",
  "Gorebyss",
  "Relicanth",
  "Luvdisc",
  "Bagon",
  "Shelgon",
  "Salamence",
  "Beldum",
  "Metang",
  "Metagross",
  "Regirock",
  "Regice",
  "Registeel",
  "Latias",
  "Latios",
  "Kyogre",
  "Groudon",
  "Rayquaza",
  "Jirachi",
  "Deoxys",
  "Turtwig",
  "Grotle",
  "Torterra",
  "Chimchar",
  "Monferno",
  "Infernape",
  "Piplup",
  "Prinplup",
  "Empoleon",
  "Starly",
  "Staravia",
  "Staraptor",
  "Bidoof",
  "Bibarel",
  "Kricketot",
  "Kricketune",
  "Shinx",
  "Luxio",
  "Luxray",
  "Budew",
  "Roserade",
  "Cranidos",
  "Rampardos",
  "Shieldon",
  "Bastiodon",
  "Burmy",
  "Wormadam",
  "Mothim",
  "Combee",
  "Vespiquen",
  "Pachirisu",
  "Buizel",
  "Floatzel",
  "Cherubi",
  "Cherrim",
  "Shellos",
  "Gastrodon",
  "Ambipom",
  "Drifloon",
  "Drifblim",
  "Buneary",
  "Lopunny",
  "Mismagius",
  "Honchkrow",
  "Glameow",
  "Purugly",
  "Chingling",
  "Stunky",
  "Skuntank",
  "Bronzor",
  "Bronzong",
  "Bonsly",
  "Mime jr.",
  "Happiny",
  "Chatot",
  "Spiritomb",
  "Gible",
  "Gabite",
  "Garchomp",
  "Munchlax",
  "Riolu",
  "Lucario",
  "Hippopotas",
  "Hippowdon",
  "Skorupi",
  "Drapion",
  "Croagunk",
  "Toxicroak",
  "Carnivine",
  "Finneon",
  "Lumineon",
  "Mantyke",
  "Snover",
  "Abomasnow",
  "Weavile",
  "Magnezone",
  "Lickilicky",
  "Rhyperior",
  "Tangrowth",
  "Electivire",
  "Magmortar",
  "Togekiss",
  "Yanmega",
  "Leafeon",
  "Glaceon",
  "Gliscor",
  "Mamoswine",
  "Porygon-z",
  "Gallade",
  "Probopass",
  "Dusknoir",
  "Froslass",
  "Rotom",
  "Uxie",
  "Mesprit",
  "Azelf",
  "Dialga",
  "Palkia",
  "Heatran",
  "Regigigas",
  "Giratina",
  "Cresselia",
  "Phione",
  "Manaphy",
  "Darkrai",
  "Shaymin",
  "Arceus",
  "Victini",
  "Snivy",
  "Servine",
  "Serperior",
  "Tepig",
  "Pignite",
  "Emboar",
  "Oshawott",
  "Dewott",
  "Samurott",
  "Patrat",
  "Watchog",
  "Lillipup",
  "Herdier",
  "Stoutland",
  "Purrloin",
  "Liepard",
  "Pansage",
  "Simisage",
  "Pansear",
  "Simisear",
  "Panpour",
  "Simipour",
  "Munna",
  "Musharna",
  "Pidove",
  "Tranquill",
  "Unfezant",
  "Blitzle",
  "Zebstrika",
  "Roggenrola",
  "Boldore",
  "Gigalith",
  "Woobat",
  "Swoobat",
  "Drilbur",
  "Excadrill",
  "Audino",
  "Timburr",
  "Gurdurr",
  "Conkeldurr",
  "Tympole",
  "Palpitoad",
  "Seismitoad",
  "Throh",
  "Sawk",
  "Sewaddle",
  "Swadloon",
  "Leavanny",
  "Venipede",
  "Whirlipede",
  "Scolipede",
  "Cottonee",
  "Whimsicott",
  "Petilil",
  "Lilligant",
  "Basculin",
  "Sandile",
  "Krokorok",
  "Krookodile",
  "Darumaka",
  "Darmanitan",
  "Maractus",
  "Dwebble",
  "Crustle",
  "Scraggy",
  "Scrafty",
  "Sigilyph",
  "Yamask",
  "Cofagrigus",
  "Tirtouga",
  "Carracosta",
  "Archen",
  "Archeops",
  "Trubbish",
  "Garbodor",
  "Zorua",
  "Zoroark",
  "Minccino",
  "Cinccino",
  "Gothita",
  "Gothorita",
  "Gothitelle",
  "Solosis",
  "Duosion",
  "Reuniclus",
  "Ducklett",
  "Swanna",
  "Vanillite",
  "Vanillish",
  "Vanilluxe",
  "Deerling",
  "Sawsbuck",
  "Emolga",
  "Karrablast",
  "Escavalier",
  "Foongus",
  "Amoonguss",
  "Frillish",
  "Jellicent",
  "Alomomola",
  "Joltik",
  "Galvantula",
  "Ferroseed",
  "Ferrothorn",
  "Klink",
  "Klang",
  "Klinklang",
  "Tynamo",
  "Eelektrik",
  "Eelektross",
  "Elgyem",
  "Beheeyem",
  "Litwick",
  "Lampent",
  "Chandelure",
  "Axew",
  "Fraxure",
  "Haxorus",
  "Cubchoo",
  "Beartic",
  "Cryogonal",
  "Shelmet",
  "Accelgor",
  "Stunfisk",
  "Mienfoo",
  "Mienshao",
  "Druddigon",
  "Golett",
  "Golurk",
  "Pawniard",
  "Bisharp",
  "Bouffalant",
  "Rufflet",
  "Braviary",
  "Vullaby",
  "Mandibuzz",
  "Heatmor",
  "Durant",
  "Deino",
  "Zweilous",
  "Hydreigon",
  "Larvesta",
  "Volcarona",
  "Cobalion",
  "Terrakion",
  "Virizion",
  "Tornadus",
  "Thundurus",
  "Reshiram",
  "Zekrom",
  "Landorus",
  "Kyurem",
  "Keldeo",
  "Meloetta",
  "Genesect",
];

fn get_gif(id: usize) -> Vec<u8> {
  match id {
    1 => include_bytes!("gifs/1.gif").to_vec(),
    2 => include_bytes!("gifs/2.gif").to_vec(),
    3 => include_bytes!("gifs/3.gif").to_vec(),
    4 => include_bytes!("gifs/4.gif").to_vec(),
    5 => include_bytes!("gifs/5.gif").to_vec(),
    6 => include_bytes!("gifs/6.gif").to_vec(),
    7 => include_bytes!("gifs/7.gif").to_vec(),
    8 => include_bytes!("gifs/8.gif").to_vec(),
    9 => include_bytes!("gifs/9.gif").to_vec(),
    10 => include_bytes!("gifs/10.gif").to_vec(),
    11 => include_bytes!("gifs/11.gif").to_vec(),
    12 => include_bytes!("gifs/12.gif").to_vec(),
    13 => include_bytes!("gifs/13.gif").to_vec(),
    14 => include_bytes!("gifs/14.gif").to_vec(),
    15 => include_bytes!("gifs/15.gif").to_vec(),
    16 => include_bytes!("gifs/16.gif").to_vec(),
    17 => include_bytes!("gifs/17.gif").to_vec(),
    18 => include_bytes!("gifs/18.gif").to_vec(),
    19 => include_bytes!("gifs/19.gif").to_vec(),
    20 => include_bytes!("gifs/20.gif").to_vec(),
    21 => include_bytes!("gifs/21.gif").to_vec(),
    22 => include_bytes!("gifs/22.gif").to_vec(),
    23 => include_bytes!("gifs/23.gif").to_vec(),
    24 => include_bytes!("gifs/24.gif").to_vec(),
    25 => include_bytes!("gifs/25.gif").to_vec(),
    26 => include_bytes!("gifs/26.gif").to_vec(),
    27 => include_bytes!("gifs/27.gif").to_vec(),
    28 => include_bytes!("gifs/28.gif").to_vec(),
    29 => include_bytes!("gifs/29.gif").to_vec(),
    30 => include_bytes!("gifs/30.gif").to_vec(),
    31 => include_bytes!("gifs/31.gif").to_vec(),
    32 => include_bytes!("gifs/32.gif").to_vec(),
    33 => include_bytes!("gifs/33.gif").to_vec(),
    34 => include_bytes!("gifs/34.gif").to_vec(),
    35 => include_bytes!("gifs/35.gif").to_vec(),
    36 => include_bytes!("gifs/36.gif").to_vec(),
    37 => include_bytes!("gifs/37.gif").to_vec(),
    38 => include_bytes!("gifs/38.gif").to_vec(),
    39 => include_bytes!("gifs/39.gif").to_vec(),
    40 => include_bytes!("gifs/40.gif").to_vec(),
    41 => include_bytes!("gifs/41.gif").to_vec(),
    42 => include_bytes!("gifs/42.gif").to_vec(),
    43 => include_bytes!("gifs/43.gif").to_vec(),
    44 => include_bytes!("gifs/44.gif").to_vec(),
    45 => include_bytes!("gifs/45.gif").to_vec(),
    46 => include_bytes!("gifs/46.gif").to_vec(),
    47 => include_bytes!("gifs/47.gif").to_vec(),
    48 => include_bytes!("gifs/48.gif").to_vec(),
    49 => include_bytes!("gifs/49.gif").to_vec(),
    50 => include_bytes!("gifs/50.gif").to_vec(),
    51 => include_bytes!("gifs/51.gif").to_vec(),
    52 => include_bytes!("gifs/52.gif").to_vec(),
    53 => include_bytes!("gifs/53.gif").to_vec(),
    54 => include_bytes!("gifs/54.gif").to_vec(),
    55 => include_bytes!("gifs/55.gif").to_vec(),
    56 => include_bytes!("gifs/56.gif").to_vec(),
    57 => include_bytes!("gifs/57.gif").to_vec(),
    58 => include_bytes!("gifs/58.gif").to_vec(),
    59 => include_bytes!("gifs/59.gif").to_vec(),
    60 => include_bytes!("gifs/60.gif").to_vec(),
    61 => include_bytes!("gifs/61.gif").to_vec(),
    62 => include_bytes!("gifs/62.gif").to_vec(),
    63 => include_bytes!("gifs/63.gif").to_vec(),
    64 => include_bytes!("gifs/64.gif").to_vec(),
    65 => include_bytes!("gifs/65.gif").to_vec(),
    66 => include_bytes!("gifs/66.gif").to_vec(),
    67 => include_bytes!("gifs/67.gif").to_vec(),
    68 => include_bytes!("gifs/68.gif").to_vec(),
    69 => include_bytes!("gifs/69.gif").to_vec(),
    70 => include_bytes!("gifs/70.gif").to_vec(),
    71 => include_bytes!("gifs/71.gif").to_vec(),
    72 => include_bytes!("gifs/72.gif").to_vec(),
    73 => include_bytes!("gifs/73.gif").to_vec(),
    74 => include_bytes!("gifs/74.gif").to_vec(),
    75 => include_bytes!("gifs/75.gif").to_vec(),
    76 => include_bytes!("gifs/76.gif").to_vec(),
    77 => include_bytes!("gifs/77.gif").to_vec(),
    78 => include_bytes!("gifs/78.gif").to_vec(),
    79 => include_bytes!("gifs/79.gif").to_vec(),
    80 => include_bytes!("gifs/80.gif").to_vec(),
    81 => include_bytes!("gifs/81.gif").to_vec(),
    82 => include_bytes!("gifs/82.gif").to_vec(),
    83 => include_bytes!("gifs/83.gif").to_vec(),
    84 => include_bytes!("gifs/84.gif").to_vec(),
    85 => include_bytes!("gifs/85.gif").to_vec(),
    86 => include_bytes!("gifs/86.gif").to_vec(),
    87 => include_bytes!("gifs/87.gif").to_vec(),
    88 => include_bytes!("gifs/88.gif").to_vec(),
    89 => include_bytes!("gifs/89.gif").to_vec(),
    90 => include_bytes!("gifs/90.gif").to_vec(),
    91 => include_bytes!("gifs/91.gif").to_vec(),
    92 => include_bytes!("gifs/92.gif").to_vec(),
    93 => include_bytes!("gifs/93.gif").to_vec(),
    94 => include_bytes!("gifs/94.gif").to_vec(),
    95 => include_bytes!("gifs/95.gif").to_vec(),
    96 => include_bytes!("gifs/96.gif").to_vec(),
    97 => include_bytes!("gifs/97.gif").to_vec(),
    98 => include_bytes!("gifs/98.gif").to_vec(),
    99 => include_bytes!("gifs/99.gif").to_vec(),
    100 => include_bytes!("gifs/100.gif").to_vec(),
    101 => include_bytes!("gifs/101.gif").to_vec(),
    102 => include_bytes!("gifs/102.gif").to_vec(),
    103 => include_bytes!("gifs/103.gif").to_vec(),
    104 => include_bytes!("gifs/104.gif").to_vec(),
    105 => include_bytes!("gifs/105.gif").to_vec(),
    106 => include_bytes!("gifs/106.gif").to_vec(),
    107 => include_bytes!("gifs/107.gif").to_vec(),
    108 => include_bytes!("gifs/108.gif").to_vec(),
    109 => include_bytes!("gifs/109.gif").to_vec(),
    110 => include_bytes!("gifs/110.gif").to_vec(),
    111 => include_bytes!("gifs/111.gif").to_vec(),
    112 => include_bytes!("gifs/112.gif").to_vec(),
    113 => include_bytes!("gifs/113.gif").to_vec(),
    114 => include_bytes!("gifs/114.gif").to_vec(),
    115 => include_bytes!("gifs/115.gif").to_vec(),
    116 => include_bytes!("gifs/116.gif").to_vec(),
    117 => include_bytes!("gifs/117.gif").to_vec(),
    118 => include_bytes!("gifs/118.gif").to_vec(),
    119 => include_bytes!("gifs/119.gif").to_vec(),
    120 => include_bytes!("gifs/120.gif").to_vec(),
    121 => include_bytes!("gifs/121.gif").to_vec(),
    122 => include_bytes!("gifs/122.gif").to_vec(),
    123 => include_bytes!("gifs/123.gif").to_vec(),
    124 => include_bytes!("gifs/124.gif").to_vec(),
    125 => include_bytes!("gifs/125.gif").to_vec(),
    126 => include_bytes!("gifs/126.gif").to_vec(),
    127 => include_bytes!("gifs/127.gif").to_vec(),
    128 => include_bytes!("gifs/128.gif").to_vec(),
    129 => include_bytes!("gifs/129.gif").to_vec(),
    130 => include_bytes!("gifs/130.gif").to_vec(),
    131 => include_bytes!("gifs/131.gif").to_vec(),
    132 => include_bytes!("gifs/132.gif").to_vec(),
    133 => include_bytes!("gifs/133.gif").to_vec(),
    134 => include_bytes!("gifs/134.gif").to_vec(),
    135 => include_bytes!("gifs/135.gif").to_vec(),
    136 => include_bytes!("gifs/136.gif").to_vec(),
    137 => include_bytes!("gifs/137.gif").to_vec(),
    138 => include_bytes!("gifs/138.gif").to_vec(),
    139 => include_bytes!("gifs/139.gif").to_vec(),
    140 => include_bytes!("gifs/140.gif").to_vec(),
    141 => include_bytes!("gifs/141.gif").to_vec(),
    142 => include_bytes!("gifs/142.gif").to_vec(),
    143 => include_bytes!("gifs/143.gif").to_vec(),
    144 => include_bytes!("gifs/144.gif").to_vec(),
    145 => include_bytes!("gifs/145.gif").to_vec(),
    146 => include_bytes!("gifs/146.gif").to_vec(),
    147 => include_bytes!("gifs/147.gif").to_vec(),
    148 => include_bytes!("gifs/148.gif").to_vec(),
    149 => include_bytes!("gifs/149.gif").to_vec(),
    150 => include_bytes!("gifs/150.gif").to_vec(),
    151 => include_bytes!("gifs/151.gif").to_vec(),
    152 => include_bytes!("gifs/152.gif").to_vec(),
    153 => include_bytes!("gifs/153.gif").to_vec(),
    154 => include_bytes!("gifs/154.gif").to_vec(),
    155 => include_bytes!("gifs/155.gif").to_vec(),
    156 => include_bytes!("gifs/156.gif").to_vec(),
    157 => include_bytes!("gifs/157.gif").to_vec(),
    158 => include_bytes!("gifs/158.gif").to_vec(),
    159 => include_bytes!("gifs/159.gif").to_vec(),
    160 => include_bytes!("gifs/160.gif").to_vec(),
    161 => include_bytes!("gifs/161.gif").to_vec(),
    162 => include_bytes!("gifs/162.gif").to_vec(),
    163 => include_bytes!("gifs/163.gif").to_vec(),
    164 => include_bytes!("gifs/164.gif").to_vec(),
    165 => include_bytes!("gifs/165.gif").to_vec(),
    166 => include_bytes!("gifs/166.gif").to_vec(),
    167 => include_bytes!("gifs/167.gif").to_vec(),
    168 => include_bytes!("gifs/168.gif").to_vec(),
    169 => include_bytes!("gifs/169.gif").to_vec(),
    170 => include_bytes!("gifs/170.gif").to_vec(),
    171 => include_bytes!("gifs/171.gif").to_vec(),
    172 => include_bytes!("gifs/172.gif").to_vec(),
    173 => include_bytes!("gifs/173.gif").to_vec(),
    174 => include_bytes!("gifs/174.gif").to_vec(),
    175 => include_bytes!("gifs/175.gif").to_vec(),
    176 => include_bytes!("gifs/176.gif").to_vec(),
    177 => include_bytes!("gifs/177.gif").to_vec(),
    178 => include_bytes!("gifs/178.gif").to_vec(),
    179 => include_bytes!("gifs/179.gif").to_vec(),
    180 => include_bytes!("gifs/180.gif").to_vec(),
    181 => include_bytes!("gifs/181.gif").to_vec(),
    182 => include_bytes!("gifs/182.gif").to_vec(),
    183 => include_bytes!("gifs/183.gif").to_vec(),
    184 => include_bytes!("gifs/184.gif").to_vec(),
    185 => include_bytes!("gifs/185.gif").to_vec(),
    186 => include_bytes!("gifs/186.gif").to_vec(),
    187 => include_bytes!("gifs/187.gif").to_vec(),
    188 => include_bytes!("gifs/188.gif").to_vec(),
    189 => include_bytes!("gifs/189.gif").to_vec(),
    190 => include_bytes!("gifs/190.gif").to_vec(),
    191 => include_bytes!("gifs/191.gif").to_vec(),
    192 => include_bytes!("gifs/192.gif").to_vec(),
    193 => include_bytes!("gifs/193.gif").to_vec(),
    194 => include_bytes!("gifs/194.gif").to_vec(),
    195 => include_bytes!("gifs/195.gif").to_vec(),
    196 => include_bytes!("gifs/196.gif").to_vec(),
    197 => include_bytes!("gifs/197.gif").to_vec(),
    198 => include_bytes!("gifs/198.gif").to_vec(),
    199 => include_bytes!("gifs/199.gif").to_vec(),
    200 => include_bytes!("gifs/200.gif").to_vec(),
    201 => include_bytes!("gifs/201.gif").to_vec(),
    202 => include_bytes!("gifs/202.gif").to_vec(),
    203 => include_bytes!("gifs/203.gif").to_vec(),
    204 => include_bytes!("gifs/204.gif").to_vec(),
    205 => include_bytes!("gifs/205.gif").to_vec(),
    206 => include_bytes!("gifs/206.gif").to_vec(),
    207 => include_bytes!("gifs/207.gif").to_vec(),
    208 => include_bytes!("gifs/208.gif").to_vec(),
    209 => include_bytes!("gifs/209.gif").to_vec(),
    210 => include_bytes!("gifs/210.gif").to_vec(),
    211 => include_bytes!("gifs/211.gif").to_vec(),
    212 => include_bytes!("gifs/212.gif").to_vec(),
    213 => include_bytes!("gifs/213.gif").to_vec(),
    214 => include_bytes!("gifs/214.gif").to_vec(),
    215 => include_bytes!("gifs/215.gif").to_vec(),
    216 => include_bytes!("gifs/216.gif").to_vec(),
    217 => include_bytes!("gifs/217.gif").to_vec(),
    218 => include_bytes!("gifs/218.gif").to_vec(),
    219 => include_bytes!("gifs/219.gif").to_vec(),
    220 => include_bytes!("gifs/220.gif").to_vec(),
    221 => include_bytes!("gifs/221.gif").to_vec(),
    222 => include_bytes!("gifs/222.gif").to_vec(),
    223 => include_bytes!("gifs/223.gif").to_vec(),
    224 => include_bytes!("gifs/224.gif").to_vec(),
    225 => include_bytes!("gifs/225.gif").to_vec(),
    226 => include_bytes!("gifs/226.gif").to_vec(),
    227 => include_bytes!("gifs/227.gif").to_vec(),
    228 => include_bytes!("gifs/228.gif").to_vec(),
    229 => include_bytes!("gifs/229.gif").to_vec(),
    230 => include_bytes!("gifs/230.gif").to_vec(),
    231 => include_bytes!("gifs/231.gif").to_vec(),
    232 => include_bytes!("gifs/232.gif").to_vec(),
    233 => include_bytes!("gifs/233.gif").to_vec(),
    234 => include_bytes!("gifs/234.gif").to_vec(),
    235 => include_bytes!("gifs/235.gif").to_vec(),
    236 => include_bytes!("gifs/236.gif").to_vec(),
    237 => include_bytes!("gifs/237.gif").to_vec(),
    238 => include_bytes!("gifs/238.gif").to_vec(),
    239 => include_bytes!("gifs/239.gif").to_vec(),
    240 => include_bytes!("gifs/240.gif").to_vec(),
    241 => include_bytes!("gifs/241.gif").to_vec(),
    242 => include_bytes!("gifs/242.gif").to_vec(),
    243 => include_bytes!("gifs/243.gif").to_vec(),
    244 => include_bytes!("gifs/244.gif").to_vec(),
    245 => include_bytes!("gifs/245.gif").to_vec(),
    246 => include_bytes!("gifs/246.gif").to_vec(),
    247 => include_bytes!("gifs/247.gif").to_vec(),
    248 => include_bytes!("gifs/248.gif").to_vec(),
    249 => include_bytes!("gifs/249.gif").to_vec(),
    250 => include_bytes!("gifs/250.gif").to_vec(),
    251 => include_bytes!("gifs/251.gif").to_vec(),
    252 => include_bytes!("gifs/252.gif").to_vec(),
    253 => include_bytes!("gifs/253.gif").to_vec(),
    254 => include_bytes!("gifs/254.gif").to_vec(),
    255 => include_bytes!("gifs/255.gif").to_vec(),
    256 => include_bytes!("gifs/256.gif").to_vec(),
    257 => include_bytes!("gifs/257.gif").to_vec(),
    258 => include_bytes!("gifs/258.gif").to_vec(),
    259 => include_bytes!("gifs/259.gif").to_vec(),
    260 => include_bytes!("gifs/260.gif").to_vec(),
    261 => include_bytes!("gifs/261.gif").to_vec(),
    262 => include_bytes!("gifs/262.gif").to_vec(),
    263 => include_bytes!("gifs/263.gif").to_vec(),
    264 => include_bytes!("gifs/264.gif").to_vec(),
    265 => include_bytes!("gifs/265.gif").to_vec(),
    266 => include_bytes!("gifs/266.gif").to_vec(),
    267 => include_bytes!("gifs/267.gif").to_vec(),
    268 => include_bytes!("gifs/268.gif").to_vec(),
    269 => include_bytes!("gifs/269.gif").to_vec(),
    270 => include_bytes!("gifs/270.gif").to_vec(),
    271 => include_bytes!("gifs/271.gif").to_vec(),
    272 => include_bytes!("gifs/272.gif").to_vec(),
    273 => include_bytes!("gifs/273.gif").to_vec(),
    274 => include_bytes!("gifs/274.gif").to_vec(),
    275 => include_bytes!("gifs/275.gif").to_vec(),
    276 => include_bytes!("gifs/276.gif").to_vec(),
    277 => include_bytes!("gifs/277.gif").to_vec(),
    278 => include_bytes!("gifs/278.gif").to_vec(),
    279 => include_bytes!("gifs/279.gif").to_vec(),
    280 => include_bytes!("gifs/280.gif").to_vec(),
    281 => include_bytes!("gifs/281.gif").to_vec(),
    282 => include_bytes!("gifs/282.gif").to_vec(),
    283 => include_bytes!("gifs/283.gif").to_vec(),
    284 => include_bytes!("gifs/284.gif").to_vec(),
    285 => include_bytes!("gifs/285.gif").to_vec(),
    286 => include_bytes!("gifs/286.gif").to_vec(),
    287 => include_bytes!("gifs/287.gif").to_vec(),
    288 => include_bytes!("gifs/288.gif").to_vec(),
    289 => include_bytes!("gifs/289.gif").to_vec(),
    290 => include_bytes!("gifs/290.gif").to_vec(),
    291 => include_bytes!("gifs/291.gif").to_vec(),
    292 => include_bytes!("gifs/292.gif").to_vec(),
    293 => include_bytes!("gifs/293.gif").to_vec(),
    294 => include_bytes!("gifs/294.gif").to_vec(),
    295 => include_bytes!("gifs/295.gif").to_vec(),
    296 => include_bytes!("gifs/296.gif").to_vec(),
    297 => include_bytes!("gifs/297.gif").to_vec(),
    298 => include_bytes!("gifs/298.gif").to_vec(),
    299 => include_bytes!("gifs/299.gif").to_vec(),
    300 => include_bytes!("gifs/300.gif").to_vec(),
    301 => include_bytes!("gifs/301.gif").to_vec(),
    302 => include_bytes!("gifs/302.gif").to_vec(),
    303 => include_bytes!("gifs/303.gif").to_vec(),
    304 => include_bytes!("gifs/304.gif").to_vec(),
    305 => include_bytes!("gifs/305.gif").to_vec(),
    306 => include_bytes!("gifs/306.gif").to_vec(),
    307 => include_bytes!("gifs/307.gif").to_vec(),
    308 => include_bytes!("gifs/308.gif").to_vec(),
    309 => include_bytes!("gifs/309.gif").to_vec(),
    310 => include_bytes!("gifs/310.gif").to_vec(),
    311 => include_bytes!("gifs/311.gif").to_vec(),
    312 => include_bytes!("gifs/312.gif").to_vec(),
    313 => include_bytes!("gifs/313.gif").to_vec(),
    314 => include_bytes!("gifs/314.gif").to_vec(),
    315 => include_bytes!("gifs/315.gif").to_vec(),
    316 => include_bytes!("gifs/316.gif").to_vec(),
    317 => include_bytes!("gifs/317.gif").to_vec(),
    318 => include_bytes!("gifs/318.gif").to_vec(),
    319 => include_bytes!("gifs/319.gif").to_vec(),
    320 => include_bytes!("gifs/320.gif").to_vec(),
    321 => include_bytes!("gifs/321.gif").to_vec(),
    322 => include_bytes!("gifs/322.gif").to_vec(),
    323 => include_bytes!("gifs/323.gif").to_vec(),
    324 => include_bytes!("gifs/324.gif").to_vec(),
    325 => include_bytes!("gifs/325.gif").to_vec(),
    326 => include_bytes!("gifs/326.gif").to_vec(),
    327 => include_bytes!("gifs/327.gif").to_vec(),
    328 => include_bytes!("gifs/328.gif").to_vec(),
    329 => include_bytes!("gifs/329.gif").to_vec(),
    330 => include_bytes!("gifs/330.gif").to_vec(),
    331 => include_bytes!("gifs/331.gif").to_vec(),
    332 => include_bytes!("gifs/332.gif").to_vec(),
    333 => include_bytes!("gifs/333.gif").to_vec(),
    334 => include_bytes!("gifs/334.gif").to_vec(),
    335 => include_bytes!("gifs/335.gif").to_vec(),
    336 => include_bytes!("gifs/336.gif").to_vec(),
    337 => include_bytes!("gifs/337.gif").to_vec(),
    338 => include_bytes!("gifs/338.gif").to_vec(),
    339 => include_bytes!("gifs/339.gif").to_vec(),
    340 => include_bytes!("gifs/340.gif").to_vec(),
    341 => include_bytes!("gifs/341.gif").to_vec(),
    342 => include_bytes!("gifs/342.gif").to_vec(),
    343 => include_bytes!("gifs/343.gif").to_vec(),
    344 => include_bytes!("gifs/344.gif").to_vec(),
    345 => include_bytes!("gifs/345.gif").to_vec(),
    346 => include_bytes!("gifs/346.gif").to_vec(),
    347 => include_bytes!("gifs/347.gif").to_vec(),
    348 => include_bytes!("gifs/348.gif").to_vec(),
    349 => include_bytes!("gifs/349.gif").to_vec(),
    350 => include_bytes!("gifs/350.gif").to_vec(),
    351 => include_bytes!("gifs/351.gif").to_vec(),
    352 => include_bytes!("gifs/352.gif").to_vec(),
    353 => include_bytes!("gifs/353.gif").to_vec(),
    354 => include_bytes!("gifs/354.gif").to_vec(),
    355 => include_bytes!("gifs/355.gif").to_vec(),
    356 => include_bytes!("gifs/356.gif").to_vec(),
    357 => include_bytes!("gifs/357.gif").to_vec(),
    358 => include_bytes!("gifs/358.gif").to_vec(),
    359 => include_bytes!("gifs/359.gif").to_vec(),
    360 => include_bytes!("gifs/360.gif").to_vec(),
    361 => include_bytes!("gifs/361.gif").to_vec(),
    362 => include_bytes!("gifs/362.gif").to_vec(),
    363 => include_bytes!("gifs/363.gif").to_vec(),
    364 => include_bytes!("gifs/364.gif").to_vec(),
    365 => include_bytes!("gifs/365.gif").to_vec(),
    366 => include_bytes!("gifs/366.gif").to_vec(),
    367 => include_bytes!("gifs/367.gif").to_vec(),
    368 => include_bytes!("gifs/368.gif").to_vec(),
    369 => include_bytes!("gifs/369.gif").to_vec(),
    370 => include_bytes!("gifs/370.gif").to_vec(),
    371 => include_bytes!("gifs/371.gif").to_vec(),
    372 => include_bytes!("gifs/372.gif").to_vec(),
    373 => include_bytes!("gifs/373.gif").to_vec(),
    374 => include_bytes!("gifs/374.gif").to_vec(),
    375 => include_bytes!("gifs/375.gif").to_vec(),
    376 => include_bytes!("gifs/376.gif").to_vec(),
    377 => include_bytes!("gifs/377.gif").to_vec(),
    378 => include_bytes!("gifs/378.gif").to_vec(),
    379 => include_bytes!("gifs/379.gif").to_vec(),
    380 => include_bytes!("gifs/380.gif").to_vec(),
    381 => include_bytes!("gifs/381.gif").to_vec(),
    382 => include_bytes!("gifs/382.gif").to_vec(),
    383 => include_bytes!("gifs/383.gif").to_vec(),
    384 => include_bytes!("gifs/384.gif").to_vec(),
    385 => include_bytes!("gifs/385.gif").to_vec(),
    386 => include_bytes!("gifs/386.gif").to_vec(),
    387 => include_bytes!("gifs/387.gif").to_vec(),
    388 => include_bytes!("gifs/388.gif").to_vec(),
    389 => include_bytes!("gifs/389.gif").to_vec(),
    390 => include_bytes!("gifs/390.gif").to_vec(),
    391 => include_bytes!("gifs/391.gif").to_vec(),
    392 => include_bytes!("gifs/392.gif").to_vec(),
    393 => include_bytes!("gifs/393.gif").to_vec(),
    394 => include_bytes!("gifs/394.gif").to_vec(),
    395 => include_bytes!("gifs/395.gif").to_vec(),
    396 => include_bytes!("gifs/396.gif").to_vec(),
    397 => include_bytes!("gifs/397.gif").to_vec(),
    398 => include_bytes!("gifs/398.gif").to_vec(),
    399 => include_bytes!("gifs/399.gif").to_vec(),
    400 => include_bytes!("gifs/400.gif").to_vec(),
    401 => include_bytes!("gifs/401.gif").to_vec(),
    402 => include_bytes!("gifs/402.gif").to_vec(),
    403 => include_bytes!("gifs/403.gif").to_vec(),
    404 => include_bytes!("gifs/404.gif").to_vec(),
    405 => include_bytes!("gifs/405.gif").to_vec(),
    406 => include_bytes!("gifs/406.gif").to_vec(),
    407 => include_bytes!("gifs/407.gif").to_vec(),
    408 => include_bytes!("gifs/408.gif").to_vec(),
    409 => include_bytes!("gifs/409.gif").to_vec(),
    410 => include_bytes!("gifs/410.gif").to_vec(),
    411 => include_bytes!("gifs/411.gif").to_vec(),
    412 => include_bytes!("gifs/412.gif").to_vec(),
    413 => include_bytes!("gifs/413.gif").to_vec(),
    414 => include_bytes!("gifs/414.gif").to_vec(),
    415 => include_bytes!("gifs/415.gif").to_vec(),
    416 => include_bytes!("gifs/416.gif").to_vec(),
    417 => include_bytes!("gifs/417.gif").to_vec(),
    418 => include_bytes!("gifs/418.gif").to_vec(),
    419 => include_bytes!("gifs/419.gif").to_vec(),
    420 => include_bytes!("gifs/420.gif").to_vec(),
    421 => include_bytes!("gifs/421.gif").to_vec(),
    422 => include_bytes!("gifs/422.gif").to_vec(),
    423 => include_bytes!("gifs/423.gif").to_vec(),
    424 => include_bytes!("gifs/424.gif").to_vec(),
    425 => include_bytes!("gifs/425.gif").to_vec(),
    426 => include_bytes!("gifs/426.gif").to_vec(),
    427 => include_bytes!("gifs/427.gif").to_vec(),
    428 => include_bytes!("gifs/428.gif").to_vec(),
    429 => include_bytes!("gifs/429.gif").to_vec(),
    430 => include_bytes!("gifs/430.gif").to_vec(),
    431 => include_bytes!("gifs/431.gif").to_vec(),
    432 => include_bytes!("gifs/432.gif").to_vec(),
    433 => include_bytes!("gifs/433.gif").to_vec(),
    434 => include_bytes!("gifs/434.gif").to_vec(),
    435 => include_bytes!("gifs/435.gif").to_vec(),
    436 => include_bytes!("gifs/436.gif").to_vec(),
    437 => include_bytes!("gifs/437.gif").to_vec(),
    438 => include_bytes!("gifs/438.gif").to_vec(),
    439 => include_bytes!("gifs/439.gif").to_vec(),
    440 => include_bytes!("gifs/440.gif").to_vec(),
    441 => include_bytes!("gifs/441.gif").to_vec(),
    442 => include_bytes!("gifs/442.gif").to_vec(),
    443 => include_bytes!("gifs/443.gif").to_vec(),
    444 => include_bytes!("gifs/444.gif").to_vec(),
    445 => include_bytes!("gifs/445.gif").to_vec(),
    446 => include_bytes!("gifs/446.gif").to_vec(),
    447 => include_bytes!("gifs/447.gif").to_vec(),
    448 => include_bytes!("gifs/448.gif").to_vec(),
    449 => include_bytes!("gifs/449.gif").to_vec(),
    450 => include_bytes!("gifs/450.gif").to_vec(),
    451 => include_bytes!("gifs/451.gif").to_vec(),
    452 => include_bytes!("gifs/452.gif").to_vec(),
    453 => include_bytes!("gifs/453.gif").to_vec(),
    454 => include_bytes!("gifs/454.gif").to_vec(),
    455 => include_bytes!("gifs/455.gif").to_vec(),
    456 => include_bytes!("gifs/456.gif").to_vec(),
    457 => include_bytes!("gifs/457.gif").to_vec(),
    458 => include_bytes!("gifs/458.gif").to_vec(),
    459 => include_bytes!("gifs/459.gif").to_vec(),
    460 => include_bytes!("gifs/460.gif").to_vec(),
    461 => include_bytes!("gifs/461.gif").to_vec(),
    462 => include_bytes!("gifs/462.gif").to_vec(),
    463 => include_bytes!("gifs/463.gif").to_vec(),
    464 => include_bytes!("gifs/464.gif").to_vec(),
    465 => include_bytes!("gifs/465.gif").to_vec(),
    466 => include_bytes!("gifs/466.gif").to_vec(),
    467 => include_bytes!("gifs/467.gif").to_vec(),
    468 => include_bytes!("gifs/468.gif").to_vec(),
    469 => include_bytes!("gifs/469.gif").to_vec(),
    470 => include_bytes!("gifs/470.gif").to_vec(),
    471 => include_bytes!("gifs/471.gif").to_vec(),
    472 => include_bytes!("gifs/472.gif").to_vec(),
    473 => include_bytes!("gifs/473.gif").to_vec(),
    474 => include_bytes!("gifs/474.gif").to_vec(),
    475 => include_bytes!("gifs/475.gif").to_vec(),
    476 => include_bytes!("gifs/476.gif").to_vec(),
    477 => include_bytes!("gifs/477.gif").to_vec(),
    478 => include_bytes!("gifs/478.gif").to_vec(),
    479 => include_bytes!("gifs/479.gif").to_vec(),
    480 => include_bytes!("gifs/480.gif").to_vec(),
    481 => include_bytes!("gifs/481.gif").to_vec(),
    482 => include_bytes!("gifs/482.gif").to_vec(),
    483 => include_bytes!("gifs/483.gif").to_vec(),
    484 => include_bytes!("gifs/484.gif").to_vec(),
    485 => include_bytes!("gifs/485.gif").to_vec(),
    486 => include_bytes!("gifs/486.gif").to_vec(),
    487 => include_bytes!("gifs/487.gif").to_vec(),
    488 => include_bytes!("gifs/488.gif").to_vec(),
    489 => include_bytes!("gifs/489.gif").to_vec(),
    490 => include_bytes!("gifs/490.gif").to_vec(),
    491 => include_bytes!("gifs/491.gif").to_vec(),
    492 => include_bytes!("gifs/492.gif").to_vec(),
    493 => include_bytes!("gifs/493.gif").to_vec(),
    494 => include_bytes!("gifs/494.gif").to_vec(),
    495 => include_bytes!("gifs/495.gif").to_vec(),
    496 => include_bytes!("gifs/496.gif").to_vec(),
    497 => include_bytes!("gifs/497.gif").to_vec(),
    498 => include_bytes!("gifs/498.gif").to_vec(),
    499 => include_bytes!("gifs/499.gif").to_vec(),
    500 => include_bytes!("gifs/500.gif").to_vec(),
    501 => include_bytes!("gifs/501.gif").to_vec(),
    502 => include_bytes!("gifs/502.gif").to_vec(),
    503 => include_bytes!("gifs/503.gif").to_vec(),
    504 => include_bytes!("gifs/504.gif").to_vec(),
    505 => include_bytes!("gifs/505.gif").to_vec(),
    506 => include_bytes!("gifs/506.gif").to_vec(),
    507 => include_bytes!("gifs/507.gif").to_vec(),
    508 => include_bytes!("gifs/508.gif").to_vec(),
    509 => include_bytes!("gifs/509.gif").to_vec(),
    510 => include_bytes!("gifs/510.gif").to_vec(),
    511 => include_bytes!("gifs/511.gif").to_vec(),
    512 => include_bytes!("gifs/512.gif").to_vec(),
    513 => include_bytes!("gifs/513.gif").to_vec(),
    514 => include_bytes!("gifs/514.gif").to_vec(),
    515 => include_bytes!("gifs/515.gif").to_vec(),
    516 => include_bytes!("gifs/516.gif").to_vec(),
    517 => include_bytes!("gifs/517.gif").to_vec(),
    518 => include_bytes!("gifs/518.gif").to_vec(),
    519 => include_bytes!("gifs/519.gif").to_vec(),
    520 => include_bytes!("gifs/520.gif").to_vec(),
    521 => include_bytes!("gifs/521.gif").to_vec(),
    522 => include_bytes!("gifs/522.gif").to_vec(),
    523 => include_bytes!("gifs/523.gif").to_vec(),
    524 => include_bytes!("gifs/524.gif").to_vec(),
    525 => include_bytes!("gifs/525.gif").to_vec(),
    526 => include_bytes!("gifs/526.gif").to_vec(),
    527 => include_bytes!("gifs/527.gif").to_vec(),
    528 => include_bytes!("gifs/528.gif").to_vec(),
    529 => include_bytes!("gifs/529.gif").to_vec(),
    530 => include_bytes!("gifs/530.gif").to_vec(),
    531 => include_bytes!("gifs/531.gif").to_vec(),
    532 => include_bytes!("gifs/532.gif").to_vec(),
    533 => include_bytes!("gifs/533.gif").to_vec(),
    534 => include_bytes!("gifs/534.gif").to_vec(),
    535 => include_bytes!("gifs/535.gif").to_vec(),
    536 => include_bytes!("gifs/536.gif").to_vec(),
    537 => include_bytes!("gifs/537.gif").to_vec(),
    538 => include_bytes!("gifs/538.gif").to_vec(),
    539 => include_bytes!("gifs/539.gif").to_vec(),
    540 => include_bytes!("gifs/540.gif").to_vec(),
    541 => include_bytes!("gifs/541.gif").to_vec(),
    542 => include_bytes!("gifs/542.gif").to_vec(),
    543 => include_bytes!("gifs/543.gif").to_vec(),
    544 => include_bytes!("gifs/544.gif").to_vec(),
    545 => include_bytes!("gifs/545.gif").to_vec(),
    546 => include_bytes!("gifs/546.gif").to_vec(),
    547 => include_bytes!("gifs/547.gif").to_vec(),
    548 => include_bytes!("gifs/548.gif").to_vec(),
    549 => include_bytes!("gifs/549.gif").to_vec(),
    550 => include_bytes!("gifs/550.gif").to_vec(),
    551 => include_bytes!("gifs/551.gif").to_vec(),
    552 => include_bytes!("gifs/552.gif").to_vec(),
    553 => include_bytes!("gifs/553.gif").to_vec(),
    554 => include_bytes!("gifs/554.gif").to_vec(),
    555 => include_bytes!("gifs/555.gif").to_vec(),
    556 => include_bytes!("gifs/556.gif").to_vec(),
    557 => include_bytes!("gifs/557.gif").to_vec(),
    558 => include_bytes!("gifs/558.gif").to_vec(),
    559 => include_bytes!("gifs/559.gif").to_vec(),
    560 => include_bytes!("gifs/560.gif").to_vec(),
    561 => include_bytes!("gifs/561.gif").to_vec(),
    562 => include_bytes!("gifs/562.gif").to_vec(),
    563 => include_bytes!("gifs/563.gif").to_vec(),
    564 => include_bytes!("gifs/564.gif").to_vec(),
    565 => include_bytes!("gifs/565.gif").to_vec(),
    566 => include_bytes!("gifs/566.gif").to_vec(),
    567 => include_bytes!("gifs/567.gif").to_vec(),
    568 => include_bytes!("gifs/568.gif").to_vec(),
    569 => include_bytes!("gifs/569.gif").to_vec(),
    570 => include_bytes!("gifs/570.gif").to_vec(),
    571 => include_bytes!("gifs/571.gif").to_vec(),
    572 => include_bytes!("gifs/572.gif").to_vec(),
    573 => include_bytes!("gifs/573.gif").to_vec(),
    574 => include_bytes!("gifs/574.gif").to_vec(),
    575 => include_bytes!("gifs/575.gif").to_vec(),
    576 => include_bytes!("gifs/576.gif").to_vec(),
    577 => include_bytes!("gifs/577.gif").to_vec(),
    578 => include_bytes!("gifs/578.gif").to_vec(),
    579 => include_bytes!("gifs/579.gif").to_vec(),
    580 => include_bytes!("gifs/580.gif").to_vec(),
    581 => include_bytes!("gifs/581.gif").to_vec(),
    582 => include_bytes!("gifs/582.gif").to_vec(),
    583 => include_bytes!("gifs/583.gif").to_vec(),
    584 => include_bytes!("gifs/584.gif").to_vec(),
    585 => include_bytes!("gifs/585.gif").to_vec(),
    586 => include_bytes!("gifs/586.gif").to_vec(),
    587 => include_bytes!("gifs/587.gif").to_vec(),
    588 => include_bytes!("gifs/588.gif").to_vec(),
    589 => include_bytes!("gifs/589.gif").to_vec(),
    590 => include_bytes!("gifs/590.gif").to_vec(),
    591 => include_bytes!("gifs/591.gif").to_vec(),
    592 => include_bytes!("gifs/592.gif").to_vec(),
    593 => include_bytes!("gifs/593.gif").to_vec(),
    594 => include_bytes!("gifs/594.gif").to_vec(),
    595 => include_bytes!("gifs/595.gif").to_vec(),
    596 => include_bytes!("gifs/596.gif").to_vec(),
    597 => include_bytes!("gifs/597.gif").to_vec(),
    598 => include_bytes!("gifs/598.gif").to_vec(),
    599 => include_bytes!("gifs/599.gif").to_vec(),
    600 => include_bytes!("gifs/600.gif").to_vec(),
    601 => include_bytes!("gifs/601.gif").to_vec(),
    602 => include_bytes!("gifs/602.gif").to_vec(),
    603 => include_bytes!("gifs/603.gif").to_vec(),
    604 => include_bytes!("gifs/604.gif").to_vec(),
    605 => include_bytes!("gifs/605.gif").to_vec(),
    606 => include_bytes!("gifs/606.gif").to_vec(),
    607 => include_bytes!("gifs/607.gif").to_vec(),
    608 => include_bytes!("gifs/608.gif").to_vec(),
    609 => include_bytes!("gifs/609.gif").to_vec(),
    610 => include_bytes!("gifs/610.gif").to_vec(),
    611 => include_bytes!("gifs/611.gif").to_vec(),
    612 => include_bytes!("gifs/612.gif").to_vec(),
    613 => include_bytes!("gifs/613.gif").to_vec(),
    614 => include_bytes!("gifs/614.gif").to_vec(),
    615 => include_bytes!("gifs/615.gif").to_vec(),
    616 => include_bytes!("gifs/616.gif").to_vec(),
    617 => include_bytes!("gifs/617.gif").to_vec(),
    618 => include_bytes!("gifs/618.gif").to_vec(),
    619 => include_bytes!("gifs/619.gif").to_vec(),
    620 => include_bytes!("gifs/620.gif").to_vec(),
    621 => include_bytes!("gifs/621.gif").to_vec(),
    622 => include_bytes!("gifs/622.gif").to_vec(),
    623 => include_bytes!("gifs/623.gif").to_vec(),
    624 => include_bytes!("gifs/624.gif").to_vec(),
    625 => include_bytes!("gifs/625.gif").to_vec(),
    626 => include_bytes!("gifs/626.gif").to_vec(),
    627 => include_bytes!("gifs/627.gif").to_vec(),
    628 => include_bytes!("gifs/628.gif").to_vec(),
    629 => include_bytes!("gifs/629.gif").to_vec(),
    630 => include_bytes!("gifs/630.gif").to_vec(),
    631 => include_bytes!("gifs/631.gif").to_vec(),
    632 => include_bytes!("gifs/632.gif").to_vec(),
    633 => include_bytes!("gifs/633.gif").to_vec(),
    634 => include_bytes!("gifs/634.gif").to_vec(),
    635 => include_bytes!("gifs/635.gif").to_vec(),
    636 => include_bytes!("gifs/636.gif").to_vec(),
    637 => include_bytes!("gifs/637.gif").to_vec(),
    638 => include_bytes!("gifs/638.gif").to_vec(),
    639 => include_bytes!("gifs/639.gif").to_vec(),
    640 => include_bytes!("gifs/640.gif").to_vec(),
    641 => include_bytes!("gifs/641.gif").to_vec(),
    642 => include_bytes!("gifs/642.gif").to_vec(),
    643 => include_bytes!("gifs/643.gif").to_vec(),
    644 => include_bytes!("gifs/644.gif").to_vec(),
    645 => include_bytes!("gifs/645.gif").to_vec(),
    646 => include_bytes!("gifs/646.gif").to_vec(),
    647 => include_bytes!("gifs/647.gif").to_vec(),
    648 => include_bytes!("gifs/648.gif").to_vec(),
    649 => include_bytes!("gifs/649.gif").to_vec(),
    _   => include_bytes!("gifs/0.gif").to_vec(),
  }
}